.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MACHINE\-USABLE\-WORDS\-GENERATOR" "1" "January 2019" "machine-usable-words-generator developers" ""
.
.SH "NAME"
\fBmachine\-usable\-words\-generator\fR \- Generate sets of English words, sorted and segregated for machine consumption
.
.SH "SYNOPSIS"
\fBmachine\-usable\-words\-generator\fR [OUT_DIR]
.
.SH "DESCRIPTION"
Generate sets of English words, sorted and segregated for machine consumption\.
.
.P
Downloads and parses a set of adjectives, nouns, and adverbs from online sources and writes them out in raw and Rust\-includable forms\.
.
.SH "OPTIONS"
OUT_DIR
.
.IP "" 4
.
.nf

Root output directory to create word subfolders in\.

Default: current working directory\.
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/machine\-usable\-words/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/machine\-usable\-words\fR>
